spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://First-Service
          predicates:
            - Path=/api/first/**
          filters:
            - name: AuthenticationFilter
        - id: second-service
          uri: lb://Second-services
          predicates:
            - Path=/api/second/**
          filters:
            - name: AuthenticationFilter

server:
  port: 8222

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway: DEBUG